apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '<cluster_name>-tls'
  namespace: default
spec:
  dnsNames:
    - <cluster_name>.example.example-develop.nl
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: production-issuer
  secretName: <cluster_name>-<example>-tls-secret
  usages:
    - digital signature
    - key encipherment
